### ISSUE TITLE
docker init: got error: Please reinstall the libzip distribution

### ISSUE THREAD

**Issue by montac** [nielsvandermolen/example-symfony-messenger#1]
When checket out 45f0b8df I've got this error from docker-init on fedora 29 when running `docker-compose up -d` 

```
checking for pkg-config... /usr/bin/pkg-config
checking for libzip... not found
configure: error: Please reinstall the libzip distribution
```

And I get it fixed by adding this line to the Dockerfile:
` libzip-dev \`

like this

```
FROM php:fpm
RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
    && docker-php-ext-install \
        pdo_mysql \
        zip
RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
COPY . /var/www/project
WORKDIR /var/www/project/
```

**Comment by montac** [comment]
I've created a tiny PR for this https://github.com/nielsvandermolen/example-symfony-messenger/pull/2

**Comment by nielsvandermolen** [comment]
Thanks & merged. Is it not needed for the php-consume container?

**Comment by montac** [comment]
Hi Niels,
Indeed, this is a new PR https://github.com/nielsvandermolen/example-symfony-messenger/pull/3

**Comment by nielsvandermolen** [comment]
Perfect!

Thanks @montac
